# Generated by Django 5.2.8 on 2025-12-01 00:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, choices=[('OBR', 'Obrigatório'), ('REG', 'Regulatório'), ('ESS', 'Essencial'), ('IMP', 'Importante')], max_length=3)),
                ('rev3_meta', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recipes.plan')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('parent', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCapex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('mes', models.PositiveSmallIntegerField()),
                ('realizado', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('previsto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensal', to='recipes.plan')),
            ],
            options={
                'ordering': ['plan__code', 'mes'],
                'unique_together': {('plan', 'year', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('valor', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('de_para', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='recipes.plan')),
            ],
            options={
                'unique_together': {('plan', 'year')},
            },
        ),
    ]
